# Form implementation generated from reading ui file 'Home_page.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName("HomePage")
        HomePage.resize(464, 388)
        HomePage.setMinimumSize(QtCore.QSize(464, 388))
        HomePage.setMaximumSize(QtCore.QSize(464, 388))
        HomePage.setDocumentMode(False)
        HomePage.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.centralwidget = QtWidgets.QWidget(parent=HomePage)
        self.centralwidget.setObjectName("centralwidget")
        self.freespace_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.freespace_btn.setGeometry(QtCore.QRect(50, 110, 151, 161))
        self.freespace_btn.setObjectName("freespace_btn")
        self.wired_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.wired_btn.setGeometry(QtCore.QRect(280, 110, 141, 161))
        self.wired_btn.setObjectName("wired_btn")
        HomePage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=HomePage)
        self.statusbar.setObjectName("statusbar")
        HomePage.setStatusBar(self.statusbar)

        self.retranslateUi(HomePage)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        _translate = QtCore.QCoreApplication.translate
        HomePage.setWindowTitle(_translate("HomePage", "MainWindow"))
        self.freespace_btn.setText(_translate("HomePage", "Free Space QKD"))
        self.wired_btn.setText(_translate("HomePage", "Wired"))
